// <auto-generated />
namespace TheChromium.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class madeaforeginkeytomemberstochoosethreestatusoptions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(madeaforeginkeytomemberstochoosethreestatusoptions));
        
        string IMigrationMetadata.Id
        {
            get { return "201709222021166_made a foregin key to members to choose three status options"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
