// <auto-generated />
namespace TheChromium.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class recreatedthemembersmodelandaddedaVIPrequirementforevents : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(recreatedthemembersmodelandaddedaVIPrequirementforevents));
        
        string IMigrationMetadata.Id
        {
            get { return "201709201408231_re-created the members model and added a VIP requirement for events"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
