// <auto-generated />
namespace TheChromium.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class createdaforeignkeyformembersmodeltoinitiateadropdownlistinviews : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createdaforeignkeyformembersmodeltoinitiateadropdownlistinviews));
        
        string IMigrationMetadata.Id
        {
            get { return "201709201932478_created a foreign key for members model to initiate a drop-down list in views"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
